# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73123e567123cd0f31cb936213dc32e397c6bd7f85d75d6b9fdf1115f8e12375d111fc31615495c8adf02d304ac035461bf36c1fa2d22d000710c2df8dd13123

test:
  secret_key_base: 69a7b0f7d9c3a26bb48bfdd3d2a891e78a862c1376fae94eabc74554029e4852e81a5d36e87e0863fe132123e527900364bbdf37848e5d63d123ec31b5bcbf53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1238b1d1fd123e9cfb4113781235f123c1239328225a8725fc962eeb45edba990555f5ef7ce18ee24dd7e0820fea54a8cc1eaf1534a7adcf5123ea3592123d9c
